import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { supabase } from "../../supabase";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogdata }) {
  console.log("data,", blogdata);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}></main>
    </>
  );
}

Home.getInitialProps = async () => {
  const { data, error } = await supabase.from("blog_posts").select("*");

  if (error) {
    console.log(error)
    throw error;
  }
  return { blogdata: data };
};
