import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <script src="./main.js"></script> */}
      </Head>
        {/* <Script src="./main.js" strategy="lazyOnload"/> */}
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>Welcome to next.js</div>
      </main>
    </>
  );
}
